name: Snyk Monitor Scanning
on:
  release:
    types: [published]
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk-scan-ci:
    uses: grafana/security-github-actions/.github/workflows/snyk_monitor.yml@c99180caef50a3654894131e8291ad6f52df9ad3 # main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
